seq_1 = input("Type sequence of comma-separated num: ")
seq_2 = input("Type another sequence of comma-separated num: ")
spl_1 = seq_1.split(',')
spl_2 = seq_2.split(',')
list_1 = list(spl_1)
tup_1 = tuple(spl_2)
print('Class of first sequence of number:', type(list_1))
print(list_1)
print('Class of second sequence of number:', type(tup_1))
print(tup_1)